package engine.representation;

//DIE REIHENFOLGE DARF NICHT VERÄNDERT WERDEN! DIE PIECETYPES MÜSSEN VOM WERTVOLLSTEN (OBEN / ALS ERSTES) ZUM NIEDERWERTIGSTEN (UNTEN / ALS LETZTES) GEORDNET SEIN!

public enum PieceType {
    KING,
    QUEEN,
    ROOK,
    BISHOP,
    KNIGHT,
    PAWN
}
